server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://192.168.30.10/base
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    request-context-attribute: request
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
    suffix: .ftl
  jpa:
    hibernate:
      ddl-auto: update